<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <Version>0.0.0.1</Version>
    <PackageProjectUrl></PackageProjectUrl>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <LoadRequiredState>2</LoadRequiredState>
    <LoadSync>true</LoadSync>
    <CanUnloadAsync>true</CanUnloadAsync>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.183" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Resources\Interfaces\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="ThreadLocalHelper.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\ShadedVertexShader.hlsl" LogicalName="ShadedVertexShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\ImageMapperVertexShader.hlsl" LogicalName="ImageMapperVertexShader.hlsl" />

      <EmbeddedResource WithCulture="false" Include="Shaders\Files\AlphaFragmentShader.hlsl" LogicalName="AlphaFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\ClippedFragmentShader.hlsl" LogicalName="ClippedFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\MirrorFragmentShader.hlsl" LogicalName="MirrorFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\ShadedFragmentShader.hlsl" LogicalName="ShadedFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\InvertAlphaFragmentShader.hlsl" LogicalName="InvertAlphaFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\TransparencyMimicFragmentShader.hlsl" LogicalName="TransparencyMimicFragmentShader.hlsl" />
      <EmbeddedResource WithCulture="false" Include="Shaders\Files\ChannelFragmentShader.hlsl" LogicalName="ChannelFragmentShader.hlsl" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Shaders\Files\nightsky.png" />
  </ItemGroup>
  <ItemGroup>
    <ClCompile Include="Shaders\Files\ChannelFragmentShader.hlsl" />
  </ItemGroup>
</Project>
